# Generated by Django 4.2.16 on 2026-09-25 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('question_type', models.CharField(choices=[('number', '数字推理'), ('figure', '图形推理'), ('logic', '逻辑判断'), ('analogy', '类比推理'), ('deduction', '演绎推理')], max_length=32)),
                ('difficulty', models.CharField(max_length=16)),
                ('stem', models.TextField()),
                ('answer', models.CharField(max_length=32)),
                ('explanation', models.TextField()),
                ('knowledge', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='questions/')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.PositiveIntegerField()),
                ('question_stem', models.CharField(blank=True, max_length=200)),
                ('issue_type', models.CharField(choices=[('stem', '题干有误'), ('answer', '答案有误'), ('explanation', '解析有误'), ('other', '其他问题')], max_length=16)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', '处理中'), ('fixed', '已修正'), ('nochange', '无需修改')], default='pending', max_length=16)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WrongBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistakes', models.PositiveIntegerField(default=1)),
                ('favorited', models.BooleanField(default=False)),
                ('last_practiced_at', models.DateField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.logicquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
