# Generated by Django 4.2.16 on 2026-09-25 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('question_type', models.CharField(choices=[('number', '数字推理'), ('figure', '图形推理'), ('logic', '逻辑判断'), ('analogy', '类比推理'), ('deduction', '演绎推理')], max_length=32)),
                ('difficulty', models.CharField(max_length=16)),
                ('stem', models.TextField()),
                ('answer', models.CharField(max_length=32)),
                ('explanation', models.TextField()),
                ('knowledge', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, upload_to='questions/')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=16, unique=True, verbose_name='报错编号')),
                ('question_id', models.PositiveIntegerField(verbose_name='题目 ID')),
                ('issue_type', models.CharField(choices=[('stem', '题干有误'), ('answer', '答案有误'), ('explanation', '解析有误'), ('other', '其他问题')], max_length=16, verbose_name='问题类型')),
                ('detail', models.CharField(max_length=500, verbose_name='补充说明')),
                ('status', models.CharField(choices=[('pending', '处理中'), ('resolved', '已修正'), ('rejected', '无需修改')], default='pending', max_length=16, verbose_name='处理状态')),
                ('handling_note', models.CharField(blank=True, default='', max_length=500, verbose_name='处理说明')),
                ('handled_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_question_reports', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '题目报错',
                'verbose_name_plural': '题目报错',
            },
        ),
        migrations.CreateModel(
            name='WrongBookEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistakes', models.PositiveIntegerField(default=1)),
                ('favorited', models.BooleanField(default=False)),
                ('last_practiced_at', models.DateField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.logicquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
        migrations.AddConstraint(
            model_name='questionreport',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('reporter', 'question_id'), name='uniq_pending_report_per_question'),
        ),
    ]
